wr("lol lol")
wr("привет")
wr("lol lol")
wr("привет")
wr("lol lol")
wr("привет")
wr("lol lol")
wr("привет")
wr("lol lol")
wr("привет")
wr("lol lol")
wr("привет")
wr("lol lol")
wr("привет")
wr("lol lol")
wr("привет")
wr("lol lol")
wr("привет")